version: '2.1'

services:
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: flask run --host 0.0.0.0 --port 8000