version: '2.1'

volumes:
  my_volume:
    driver: local

services:
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env

    volumes:
      - /usr/local/acts:/webapp/static/acts
      - /usr/local/db:/webapp
    command: flask run --host 0.0.0.0 --port 8000
