"""Initial migration

Revision ID: 22e2e73291b3
Revises: 
Create Date: 2025-04-10 09:42:16.987836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e2e73291b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_number', sa.Integer(), nullable=False),
    sa.Column('member_fee', sa.Integer(), nullable=True),
    sa.Column('targeted_fee', sa.Integer(), nullable=True),
    sa.Column('electricity_payments', sa.Integer(), nullable=True),
    sa.Column('published', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('area_number'),
    comment='Общая финансовая таблица, загружаемая извне в ЛК у админа'
    )
    op.create_table('news_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица с новостями на главной странице'
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_table_area_number'), ['area_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_table_area_number'))

    op.drop_table('user_table')
    op.drop_table('news_table')
    op.drop_table('financial_data')
    # ### end Alembic commands ###
