"""Редактирование моделей в соответствии с требованиями типизации и PEP

Revision ID: 64601547b400
Revises: 22e2e73291b3
Create Date: 2025-04-10 20:56:42.387927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64601547b400'
down_revision = '22e2e73291b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('area_number', sa.Integer(), nullable=False, comment='Идентификатор участка'),
    sa.Column('member_fee', sa.Integer(), nullable=True, comment='Баланс участка по членским взносам'),
    sa.Column('targeted_fee', sa.Integer(), nullable=True, comment='Баланс участка по целевым взносам'),
    sa.Column('electricity_payments', sa.Integer(), nullable=True, comment='Баланс участка за электроэнергию'),
    sa.Column('published', sa.Date(), nullable=False, comment='Дата публикации финансовых данных'),
    sa.PrimaryKeyConstraint('id'),
    comment='Общая финансовая таблица, загружаемая извне в ЛК пользователей в админ-панели'
    )
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_area_number'), ['area_number'], unique=True)

    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи новости'),
    sa.Column('published', sa.DateTime(), nullable=False, comment='Дата и время публикации'),
    sa.Column('title', sa.String(), nullable=False, comment='Заголовок новости'),
    sa.Column('text', sa.String(), nullable=True, comment='Полный текст новости'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица с новостями на главной странице'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('area_number', sa.Integer(), nullable=False, comment='Уникальный номер участка'),
    sa.Column('email', sa.String(), nullable=False, comment='Адрес электронной почты пользователя'),
    sa.Column('phone', sa.String(), nullable=True, comment='Номер телефона пользователя'),
    sa.Column('password', sa.String(), nullable=False, comment='Хэшированный пароль пользователя'),
    sa.Column('role', sa.String(), nullable=True, comment="Роль пользователя (например, 'admin' или 'user')"),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_area_number'), ['area_number'], unique=True)

    op.drop_table('financial_data')
    op.drop_table('news_table')
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index('ix_user_table_area_number')

    op.drop_table('user_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_number', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_index('ix_user_table_area_number', ['area_number'], unique=1)

    op.create_table('news_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('published', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area_number', sa.INTEGER(), nullable=False),
    sa.Column('member_fee', sa.INTEGER(), nullable=True),
    sa.Column('targeted_fee', sa.INTEGER(), nullable=True),
    sa.Column('electricity_payments', sa.INTEGER(), nullable=True),
    sa.Column('published', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('area_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_area_number'))

    op.drop_table('user')
    op.drop_table('news')
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_area_number'))

    op.drop_table('finance')
    # ### end Alembic commands ###
