"""Удаление поля с телефоном пользователя из БД

Revision ID: 669acda2e1a3
Revises: 64601547b400
Create Date: 2025-04-28 13:38:31.365469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669acda2e1a3'
down_revision = '64601547b400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
